# Generated by Django 4.2 on 2023-04-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
